import Head from 'next/head'
import Header from './components/Header';
import Expertise from './components/Expertise';
import Profile from './components/Profile';
import * as C from './styles';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hamilton Ramos - Advocacia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <C.Container>
          <C.Area>
            <Header/>
            <Expertise/>
            <Profile/>
          </C.Area>
        </C.Container>
      </main>

      <footer>

      </footer>
    </div>
  )
}
